# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v6.3.0
      with:
        install-only: true

    - name: Install Just
      uses: extractions/setup-just@v3

    - name: Test
      run: just test

    - name: Build Snapshot
      run: just snapshot

